name: flutter_colored_progress_indicators
description: An alternate animated progress indicator widget for flutter's CircularProgressIndicator and LinearProgressIndicator with Google color accents.
version: 1.2.0
homepage: https://github.com/Abhi011999/flutter_colored_progress_indicators
repository: https://github.com/Abhi011999/flutter_colored_progress_indicators

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter